### PR TITLE
Create standing-bear-silhouette.png

### PR DESCRIPTION
**Pull request by Alfystar**
Is the missing image from the Trailhead:
https://trailhead.salesforce.com/content/learn/projects/lwc-build-flexible-apps/record-list?trail_id=build-lightning-web-components&trailmix_creator_id=cdicurz&trailmix_slug=get-started

### CODE REVIEW

**Comment by Alfystar** [comment]
That was an error, you have to copy the image and add it also here

**Comment by pozil** [comment]
I just double checked and the project works fine as-is.
Note that the instructions changed a couple of weeks ago and the image used to be located  in
`staticresources/ursus_park/img/standing-bear-silhouette.png` but it's no longer the case in the current instructions.

**Comment by Alfystar** [comment]
I follow the instruction and in some point is use img/ and in other not

If the error for you is in the Trailhead, please talk about this problem at the right person

**Comment by pozil** [comment]
Thanks for letting me know, I forgot to update some instructions in Trailhead. 
The fix should be deployed on Trailhead next Wednesday.

**Pull request closed without merging**
